# Site settings
author: Zachary Johnson
title: Software Engineer (in progress)
header-img: img/home-bg.png
email: zacharymjohnson2@gmail.com
copyright_name: Zachary Johnson
description: > # this means to ignore newlines until "baseurl:"
  My Journey with The Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zmjohnson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
